// pluto-marketing/src/views/Signup.vue
<template>
  <div class="signup-page">
    <div class="signup-container">
      <div class="signup-box">
        <div class="logo-section">
          <h1>Plutoo</h1>
          <p>Start your 14-day free trial</p>
        </div>

        
        <form @submit.prevent="handleSignup" class="signup-form">
          <input v-model="form.full_name" type="text" placeholder="Full name" required />
          <input v-model="form.email" type="email" placeholder="Work email" required />
          <input v-model="form.company_name" type="text" placeholder="Company name" required />
          <input v-model="form.password" type="password" placeholder="Password (min. 8 characters)" required minlength="8" />

          <button type="submit" class="signup-btn" :disabled="loading">
            {{ loading ? 'Creating account...' : 'Get Started' }}
          </button>
        </form>

        <p v-if="error" class="error">{{ error }}</p>

        <p class="terms">By signing up, you agree to our <router-link to="/terms">Terms</router-link> and <router-link to="/privacy">Privacy Policy</router-link></p>
        <p class="login">Already have an account? <a href="https://dashboard.plutoo.chat/">Sign in</a></p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useSeo } from '../composables/useSeo'

useSeo({
  title: 'Start Free Trial | Plutoo AI Customer Support',
  description: 'Start your 14-day free trial of Plutoo AI customer support. No credit card required.',
  keywords: 'free trial, signup, AI customer support'
})

const router = useRouter()
const loading = ref(false)
const error = ref('')

const form = ref({
  full_name: '',
  email: '',
  company_name: '',
  password: ''
})

const handleSignup = async () => {
  loading.value = true
  error.value = ''

  try {
    const response = await fetch(`${import.meta.env.VITE_BACKEND_URL}/auth/signup`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        full_name: form.value.full_name,
        email: form.value.email,
        company_name: form.value.company_name,
        password: form.value.password
      })
    })

    const data = await response.json()

    if (!response.ok) {
      throw new Error(data.detail || 'Signup failed')
    }

    // Store user data
    localStorage.setItem('pluto_user', JSON.stringify({
      ...data.user,
      full_name: form.value.full_name,
      company_name: form.value.company_name
    }))

    // Redirect to success page with bot token
    router.push(`/signup-success?token=${data.user.bot_token}`)

  } catch (err) {
    error.value = err.message || 'Something went wrong. Please try again.'
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.signup-page {
  min-height: 100vh;
  background: #fafafa;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 2rem;
}

.signup-container {
  width: 100%;
  max-width: 420px;
}

.signup-box {
  background: white;
  border-radius: 12px;
  padding: 3rem 2.5rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.logo-section {
  text-align: center;
  margin-bottom: 2rem;
}

.logo-section h1 {
  font-size: 2rem;
  font-weight: 800;
  color: #1a1a1a;
  margin-bottom: 0.5rem;
}

.logo-section p {
  color: #64748b;
  font-size: 1rem;
}

.signup-form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  margin-bottom: 1.5rem;
}

.signup-form input {
  padding: 0.875rem 1rem;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  font-size: 0.95rem;
  transition: all 0.2s;
}

.signup-form input:focus {
  outline: none;
  border-color: #2ED0E6;
  box-shadow: 0 0 0 3px rgba(46, 208, 230, 0.1);
}

.signup-btn {
  padding: 0.875rem;
  background: linear-gradient(135deg, #2C3E50 0%, #2ED0E6 100%);
  color: white;
  border: none;
  border-radius: 8px;
  font-weight: 600;
  font-size: 1rem;
  cursor: pointer;
  transition: all 0.2s;
  margin-top: 0.5rem;
}

.signup-btn:hover:not(:disabled) {
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(46, 208, 230, 0.3);
}

.signup-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.error {
  color: #ef4444;
  font-size: 0.9rem;
  text-align: center;
  margin-bottom: 1rem;
  padding: 0.75rem;
  background: #fee2e2;
  border-radius: 6px;
}

.terms {
  text-align: center;
  font-size: 0.85rem;
  color: #64748b;
  margin-bottom: 1rem;
}

.terms a {
  color: #2ED0E6;
  text-decoration: none;
}

.terms a:hover {
  text-decoration: underline;
}

.login {
  text-align: center;
  font-size: 0.9rem;
  color: #64748b;
  padding-top: 1.5rem;
  border-top: 1px solid #e2e8f0;
}

.login a {
  color: #2ED0E6;
  text-decoration: none;
  font-weight: 600;
}

.login a:hover {
  text-decoration: underline;
}

@media (max-width: 480px) {
  .signup-box {
    padding: 2rem 1.5rem;
  }

  .logo-section h1 {
    font-size: 1.75rem;
  }
}
</style>

// src/app/signup/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { authAPI } from '@/lib/api';
import { setToken, setUser } from '@/lib/auth';
import { useDashboardStore } from '@/store';
import toast from 'react-hot-toast';

export default function SignupPage() {
  const router = useRouter();
  const { setUser: setStoreUser } = useDashboardStore();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    confirmPassword: '',
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.name || !formData.email || !formData.password || !formData.confirmPassword) {
      toast.error('Please fill in all fields');
      return;
    }

    if (formData.password !== formData.confirmPassword) {
      toast.error('Passwords do not match');
      return;
    }

    if (formData.password.length < 6) {
      toast.error('Password must be at least 6 characters');
      return;
    }

    setLoading(true);
    try {
      const response = await authAPI.signup(formData.name, formData.email, formData.password);
      const { token, user } = response.data;
      
      setToken(token);
      setUser(user);
      setStoreUser(user);
      
      toast.success('Account created successfully');
      router.push('/dashboard');
    } catch (error: any) {
      toast.error(error.response?.data?.message || 'Signup failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-slate-50">
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle className="text-2xl text-center">Create Account</CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="text-sm font-medium text-slate-900">Name</label>
              <Input
                type="text"
                placeholder="Your name"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                className="mt-1"
              />
            </div>

            <div>
              <label className="text-sm font-medium text-slate-900">Email</label>
              <Input
                type="email"
                placeholder="your@email.com"
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                className="mt-1"
              />
            </div>

            <div>
              <label className="text-sm font-medium text-slate-900">Password</label>
              <Input
                type="password"
                placeholder="••••••••"
                value={formData.password}
                onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                className="mt-1"
              />
            </div>

            <div>
              <label className="text-sm font-medium text-slate-900">Confirm Password</label>
              <Input
                type="password"
                placeholder="••••••••"
                value={formData.confirmPassword}
                onChange={(e) => setFormData({ ...formData, confirmPassword: e.target.value })}
                className="mt-1"
              />
            </div>

            <Button type="submit" disabled={loading} className="w-full">
              {loading ? 'Creating account...' : 'Sign Up'}
            </Button>
          </form>

          <div className="mt-4 text-center text-sm text-slate-600">
            Already have an account?{' '}
            <Link href="/login" className="text-black font-medium hover:underline">
              Login
            </Link>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
